config/routes.rb
Rails.application.routes.draw do
  get 'projects/dashboard'
  get 'projects/create'
  get 'projects/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, :state, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
  
  def new 
  end

  def dashboard
    if params[:state].present?
      @projects = Project.where('state = ?', params[:state])
    else
      @projects = Project.all
    end
    
  end

  def create
    
    @project = Project.create(
      name: params[:name],
      state: params[:state],
      description: params[:description],
      starts_on: params[:starts_on],
      ends_on: params[:ends_on]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
        El proyecto no pudo ser creado por las siguientes razones:
    </h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<h1> Projecto creado con éxito </h1>
<%= link_to "Dashboard", projects_dashboard_path%>

app/views/projects/dashboard.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
  <form class="form-inline">
    Buscar Proyectos en estado: 
  <select name="state">
                <option value=""></option>
                <option value="propuesta">Propuesta</option>
                <option value="en progreso">En progreso</option>
                <option value="terminado">Terminado</option>
            </select>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
<table class="table">
  <tr>
    <th>Nombre</th>
    <th>Estado</th>
    <th>Descripción</th>
    <th>Comienzo</th>
    <th>Fin</th>
  </tr>    
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %> </td>
      <td><%= project.state %> </td>
      <td><%= project.description %> </td>
      <td><%= project.starts_on %> </td>
      <td><%= project.ends_on %> </td>
    </tr>
  <% end %>
</table>
<%= link_to "Nuevo Proyecto", projects_new_path%>

app/views/projects/new.html.erb
<h1> Crear proyecto </h1>
<%project = Project.new%>
<form method="get" action="/projects/create">
    Nombre: <input name="name" />
    Estado: <select name="state">
                <option value="propuesta">Propuesta</option>
                <option value="en progreso">En progreso</option>
                <option value="terminado">Terminado</option>
            </select>
    Descripción: <textarea name="description"></textarea>
    Comienzo: <input name="starts_on" type="date"/>
    Fin: <input name="ends_on" type="date"/>
    <input type="submit" value="Guardar">  
</form>